version: '3.6'

services:
  telemetry_ts_collector_server:
    container_name: telemetry_ts
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8019:8019
    networks:
      - orione_network

networks:
  orione_network:
    external: true