version: '3'

services:
  telemetry_java_collector_service:
    container_name: telemetry_java
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8013:8013
    networks:
      - orione_network

networks:
  orione_network:
    external: true