version: '3'

services:
  orionedbmsservice:
    container_name: telemetry_postgres
    image: postgres:15.1
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    restart: always
    command: -p 5555
    ports:
      - 5555:5555
    networks:
      - orione_network

networks:
  orione_network:
    name: orione_network
