version: '3'

services:
  telemetry_rust_no_orm_collector_service:
    container_name: telemetry_rust_no_orm
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8021:8021
    networks:
      - orione_network

networks:
  orione_network:
    external: true
