version: '3'

services:
  telemetry_rust_collector_service:
    container_name: telemetry_rust
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8017:8017
    networks:
      - orione_network

networks:
  orione_network:
    external: true